# Copyright (C) 2010-2018 CEA/DAM
# Copyright (C) 2010-2018 Laurent Nguyen <laurent.nguyen@cea.fr>
#
# This file is part of HP2P.
#
# This software is governed by the CeCILL-C license under French law and
# abiding by the rules of distribution of free software.  You can  use,
# modify and/ or redistribute the software under the terms of the CeCILL-C
# license as circulated by CEA, CNRS and INRIA at the following URL
# "http://www.cecill.info".

# \file      .travis.yml
# \author    Laurent Nguyen <laurent.nguyen@cea.fr>
# \version   3.2
# \date      01 February 2018
# \brief     Travis file for CI (see travis-ci.org)
#
# \details   No

language: cpp

matrix:
  include:
     - env: TESTNAME="OMPI"
       addons:
         apt:
           packages:
             - openmpi-common
             - openmpi-bin
             - libopenmpi-dev
             - python
       compiler: gcc
       before_script:
         - export OMPI_CC=$CC
         - export OMPI_CXX=$CXX
         - mpicc --version
         - mpic++ --version
     - env: TESTNAME="OMPI"
       addons:
         apt:
           packages:
             - openmpi-common
             - openmpi-bin
             - libopenmpi-dev
             - python
       compiler: clang
       before_script:
         - export OMPI_CC=$CC
         - export OMPI_CXX=$CXX
         - mpicc --version
         - mpic++ --version
     - env: TESTNAME="MPICH"
       addons:
         apt:
           packages:
             - mpich2
             - libmpich-dev
             - python
       compiler: gcc
       before_script:
         - export MPICH_CC=$CC
         - export MPICH_CXX=$CXX
         - mpicc --version
         - mpic++ --version
     - env: TESTNAME="MPICH"
       addons:
         apt:
           packages:
             - mpich2
             - libmpich-dev
             - python
       compiler: clang
       before_script:
         - export MPICH_CC=$CC
         - export MPICH_CXX=$CXX
         - mpicc --version
         - mpic++ --version
 
install: true

script: ./autogen.sh && ./configure --prefix=$HOME/hp2p CXX=mpic++ && make && make install

